env:
    contexts:
        - authentication:
            method: form
            parameters:
                loginPageUrl: http://testhtml5.vulnweb.com/#/popular
                loginRequestBody: username={%username%}&password={%password%}
                loginRequestUrl: http://testhtml5.vulnweb.com/login
            verification:
                loggedInRegex: Logout
                loggedOutRegex: Login
                method: response
                pollFrequency: 60
                pollPostData: ""
                pollUnits: requests
                pollUrl: ""
          excludePaths: []
          includePaths:
            - http://testhtml5.vulnweb.com/.*
          name: Default Context
          sessionManagement:
            method: cookie
            parameters: {}
          technology:
            exclude: []
          urls:
            - http://testhtml5.vulnweb.com/
          users:
            - credentials:
                password: admin
                username: admin
              name: test_user
    parameters:
        failOnError: true
        failOnWarning: false
        progressToStdout: true
    vars: {}
jobs:
    - name: passiveScan-config
      parameters:
        enableTags: false
        scanOnlyInScope: true
      rules: []
      type: passiveScan-config
    - name: spider
      parameters:
        context: Default Context
        maxChildren: 0
        maxDepth: 0
        maxDuration: 0
        url: ""
        user: test_user
      type: spider
    - name: spiderAjax
      parameters:
        context: Default Context
        maxCrawlDepth: 10
        maxDuration: 60
        numberOfBrowsers: 1
        runOnlyIfModern: false
        url: ""
        user: test_user
      type: spiderAjax
    - name: passiveScan-wait
      parameters: {}
      type: passiveScan-wait
    - name: activeScan
      parameters:
        context: Default Context
        maxRuleDurationInMins: 0
        maxScanDurationInMins: 0
        policy: ""
        user: test_user
      policyDefinition:
        defaultStrength: medium
        defaultThreshold: medium
        rules: []
      type: activeScan
    - name: report-pdf
      parameters:
        reportDescription: ""
        reportDir: /demo/test_output/dast-output-2751189219
        reportFile: ZAP-Report
        reportTitle: ZAP Scanning Report
        template: traditional-pdf
      type: report
    - name: report
      parameters:
        reportDir: /demo/test_output/dast-output-2751189219
        reportFile: ZAP-Report
        template: traditional-json-plus
      type: report
