name: Checkmarx One dast-scan

on:
  push:
    branches:
      - main


jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Check current directory
        run: pwd
      - name: Chown
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: List files
        run: ls -laR
        
      # Scan Iac with kics
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v2.3.0
        env:
          CX_APIKEY: ${{ secrets.CX_ONE_API_KEY }}
        with:
          command: "web"
          config: "./web.yaml"
          base_url: "https://anz.ast.checkmarx.net/"
          #environment_id: "341bb9a2-54a3-445e-8b67-f34a15212e9e"
          environment_id: "99905b1f-a777-40bd-90b0-00aad3b27fca"
          output: dast-output
          fail_on: "HIGH"
          verbose: true
          
      - name: List files
        run: ls -laR
        
      - uses: actions/upload-artifact@v3
        name: Upload Logs
        with:
            name: report
            path: dast-output/*/*.*


            
